FROM node:20-alpine AS builder

WORKDIR /app

RUN npm install -g bun@latest

COPY package.json bun.lockb ./

RUN bun install --frozen-lockfile

COPY . .

RUN bun run build

FROM node:20-alpine AS production

WORKDIR /app

COPY --from=builder /app/.next/standalone ./.next/standalone
COPY --from=builder /app/public ./.next/standalone/public
COPY --from=builder /app/.next/static ./.next/standalone/.next/static

EXPOSE 3000

CMD [ "node", ".next/standalone/server.js" ]
