FROM node:20-alpine AS builder

WORKDIR /app

RUN npm install -g pnpm@latest typescript

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm dlx prisma generate && pnpm build

FROM node:20-alpine AS production

WORKDIR /app

COPY --from=builder /app/package.json /app/pnpm-lock.yaml ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 8082

CMD [ "node", "dist/index.js" ]
